- name: Copy nginx conf file
  template: src=nginx.j2  dest=/etc/nginx/nginx.conf owner=root mode=0644

- name: Disable Default site
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Complete Site Configuration 
  template: src=site.j2 dest=/etc/nginx/sites-available/site.conf owner=root mode=0644

- name: Enable site 
  file: state=link src=/etc/nginx/sites-available/site.conf dest=/etc/nginx/sites-enabled/site.conf

- name: Service Nginx Reload 
  service: name=nginx state=reloaded 

