---
- name: Add Nginx repository 
  template: src=centos.repo dest=/etc/yum.repos.d/nginx.repo owner=root group=root mode=0644

- name: Nginx Installation on Centos 
  yum: name=nginx state=installed 
